### PR TITLE
Fix divison by zero

### LINKED ISSUE #23: Division by zero
When executing the WP-Cron, get those errors.

```
PHP Warning:  Division by zero in /webs/example.com/wp-content/plugins/mariadb-health-checks/inc/App/ExecutionTime.php on line 14
Warning: Division by zero in /webs/example.com/wp-content/plugins/mariadb-health-checks/inc/App/ExecutionTime.php on line 14
```

### PR DESCRIPTION
**Pull request by javiercasares**
Fix #23

### CODE REVIEW

File: inc/App/ExecutionTime.php [hunk 1]
```diff
@@ -11,7 +11,11 @@ function __construct() {
 	public static function save_average_query_execution_time() {
 		global $wpdb;
 
-		$average = $wpdb->total_query_time / $wpdb->num_queries;
+		$average = null;
+
+		if( !empty( $wpdb->total_query_time ) && !empty( $wpdb->num_queries ) && $wpdb->num_queries > 0 ) {
+			$average = $wpdb->total_query_time / $wpdb->num_queries;
+		}
```
Comment (LinuxJedi) [inline inc/App/ExecutionTime.php]: I would argue that the divide by zero means that there have been no database queries in this run. Which means we shouldn't try to save (`NULL`, `0`) to the DB as it would not be useful for the graph / stats, we should just return if `num_queries` is `0` I think.

Open to discussion over it though.

**Review by LinuxJedi — CHANGES_REQUESTED** [review]

**Comment by javiercasares** [comment]
Maybe this is better...

**Review by LinuxJedi — APPROVED** [review]
Excellent! Thank you :)
